baseurl = "/"
relativeurls = true
disqusShortname = "datathinkio"
languageCode = "en-us"
title = "Data Think"
description = "Thoughts about data and visualization"
theme = "hugo-future-imperfect"
googleAnalytics = ""
publishDir = "../datathink"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/byuistats/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/groups/42868"

[params]
    description = "Thoughts about data and visualization"


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

