---
title: What is in a Name?
author: J. Hathaway
date: '2017-04-26'
slug: what-is-in-a-name
categories:
  - Data Science
tags: []
description: ''
featured: ''
featuredalt: ''
featuredpath: ''
linktitle: ''
---

I remember as a kid hearing the word **engineer** being tacked on the end of every job. I remember a few kids joking about the [garbageman](https://en.wikipedia.org/wiki/Waste_collector){target="blank"} being called a **sanitation engineer**. Coming from a [National Lab](http://www.pnnl.gov/){target="blank"} I felt the pressure to call myself a scientist and sometimes wondered why I didn't get to [wear cool glasses](https://www.flickr.com/photos/pnnl/4295283153/){target="blank"}. However, calling myself a statistical scientist felt a little weird.  Towards the end of my employment at PNNL the phrase **data scientist** started to take off.  I liked the title as I felt it communicated a little better to others my work (although I saw it used rather loosely by quite a few people).

Ever since I finished my graduate degree in statistics, I have tried to come up with different names to describe what I do. I am sure others have done this as well as very few people have experience with statisticians and their profession.  I thought it might be fun to list some of them.  I may even post about some of the names as I think the names highlight the different skills a data scientists needs.

* **Data Poet**
* **Data Artist**
* **Data Whisperer** - [I help [Data] with people problems](http://www.imdb.com/title/tt0119314/quotes){target="blank"}
* **Data Wrangler**
* **Data Journaler**

